# Analyse Exploratoire

### Import des modules

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### Analyse Exploratoire

In [ ]:
building_consumption = pd.read_csv("data/raw/2016_Building_Energy_Benchmarking.csv")

#### Audit du dataset

In [30]:
# Premiers pas sur le jeu de données
# Audit pour avoir le maximum d'infos

# les dimensions 
building_consumption.shape

(3376, 46)

In [31]:
# Les informations générales sur le dataset , permet aussi de voir ou sont les valeurs nulles
building_consumption.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3376 entries, 0 to 3375
Data columns (total 46 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   OSEBuildingID                    3376 non-null   int64
 1   DataYear                         3376 non-null   int64
 2   BuildingType                     3376 non-null   object
 3   PrimaryPropertyType              3376 non-null   object
 4   PropertyName                     3376 non-null   object
 5   Address                          3376 non-null   object
 6   City                             3376 non-null   object
 7   State                            3376 non-null   object
 8   ZipCode                          3360 non-null   float64
 9   TaxParcelIdentificationNumber    3376 non-null   object
 10  CouncilDistrictCode              3376 non-null   int64
 11  Neighborhood                     3376 non-null   object
 12  Latitude                         3376 non-null   float64
 13  Longitude                        3376 non-null   float64
 14  YearBuilt                        3376 non-null   int64
 15  NumberofBuildings                3368 non-null   float64
 16  NumberofFloors                   3376 non-null   int64
 17  PropertyGFATotal                 3376 non-null   int64
 18  PropertyGFAParking               3376 non-null   int64
 19  PropertyGFABuilding(s)           3376 non-null   int64
 20  ListOfAllPropertyUseTypes        3367 non-null   object
 21  LargestPropertyUseType           3356 non-null   object
 22  LargestPropertyUseTypeGFA        3356 non-null   float64
 23  SecondLargestPropertyUseType     1679 non-null   object
 24  SecondLargestPropertyUseTypeGFA  1679 non-null   float64
 25  ThirdLargestPropertyUseType      596 non-null    object
 26  ThirdLargestPropertyUseTypeGFA   596 non-null    float64
 27  YearsENERGYSTARCertified         119 non-null    object
 28  ENERGYSTARScore                  2533 non-null   float64
 29  SiteEUI(kBtu/sf)                 3369 non-null   float64
 30  SiteEUIWN(kBtu/sf)               3370 non-null   float64
 31  SourceEUI(kBtu/sf)               3367 non-null   float64
 32  SourceEUIWN(kBtu/sf)             3367 non-null   float64
 33  SiteEnergyUse(kBtu)              3371 non-null   float64
 34  SiteEnergyUseWN(kBtu)            3370 non-null   float64
 35  SteamUse(kBtu)                   3367 non-null   float64
 36  Electricity(kWh)                 3367 non-null   float64
 37  Electricity(kBtu)                3367 non-null   float64
 38  NaturalGas(therms)               3367 non-null   float64
 39  NaturalGas(kBtu)                 3367 non-null   float64
 40  DefaultData                      3376 non-null   bool
 41  Comments                         0 non-null      float64
 42  ComplianceStatus                 3376 non-null   object
 43  Outlier                          32 non-null     object
 44  TotalGHGEmissions                3367 non-null   float64
 45  GHGEmissionsIntensity            3367 non-null   float64
dtypes: bool(1), float64(22), int64(8), object(15)
memory usage: 1.2+ MB

In [33]:
# pour avoir plus d'infos sur les nulls 
# compte colonne par colonne 
df_nulls = building_consumption.isna().sum().reset_index()
df_nulls.columns = ["variable", "nb_nulls"]
df_nulls

                           variable  nb_nulls
0                     OSEBuildingID         0
1                          DataYear         0
2                      BuildingType         0
3               PrimaryPropertyType         0
4                      PropertyName         0
5                           Address         0
6                              City         0
7                             State         0
8                           ZipCode        16
9     TaxParcelIdentificationNumber         0
10              CouncilDistrictCode         0
11                     Neighborhood         0
12                         Latitude         0
13                        Longitude         0
14                        YearBuilt         0
15                NumberofBuildings         8
16                   NumberofFloors         0
17                 PropertyGFATotal         0
18               PropertyGFAParking         0
19           PropertyGFABuilding(s)         0
20        ListOfAllPropertyUseTypes         9
21           LargestPropertyUseType        20
22        LargestPropertyUseTypeGFA        20
23     SecondLargestPropertyUseType      1697
24  SecondLargestPropertyUseTypeGFA      1697
25      ThirdLargestPropertyUseType      2780
26   ThirdLargestPropertyUseTypeGFA      2780
27         YearsENERGYSTARCertified      3257
28                  ENERGYSTARScore       843
29                 SiteEUI(kBtu/sf)         7
30               SiteEUIWN(kBtu/sf)         6
31               SourceEUI(kBtu/sf)         9
32             SourceEUIWN(kBtu/sf)         9
33              SiteEnergyUse(kBtu)         5
34            SiteEnergyUseWN(kBtu)         6
35                   SteamUse(kBtu)         9
36                 Electricity(kWh)         9
37                Electricity(kBtu)         9
38               NaturalGas(therms)         9
39                 NaturalGas(kBtu)         9
40                      DefaultData         0
41                         Comments      3376
42                 ComplianceStatus         0
43                          Outlier      3344
44                TotalGHGEmissions         9
45            GHGEmissionsIntensity         9

In [32]:
# nb de lignes en doublon (lignes completes)
building_consumption.duplicated().sum()

np.int64(0)

In [29]:
# On regarde le nombre de valeurs manquantes par colonne ainsi que leur type 
building_consumption.describe(include="all")

,OSEBuildingID,DataYear,BuildingType,PrimaryPropertyType,PropertyName,Address,City,State,ZipCode,TaxParcelIdentificationNumber,...,Electricity(kWh),Electricity(kBtu),NaturalGas(therms),NaturalGas(kBtu),DefaultData,Comments,ComplianceStatus,Outlier,TotalGHGEmissions,GHGEmissionsIntensity
count,3376.000000,3376.0,3376,3376,3376,3376,3376,3376,3360.000000,3376,...,3.367000e+03,3.367000e+03,3.367000e+03,3.367000e+03,3376,0.0,3376,32,3367.000000,3367.000000
unique,NaN,NaN,8,24,3362,3354,1,1,NaN,3268,...,NaN,NaN,NaN,NaN,2,NaN,4,2,NaN,NaN
top,NaN,NaN,NonResidential,Low-Rise Multifamily,Northgate Plaza,2600 SW Barton St,Seattle,WA,NaN,1625049001,...,NaN,NaN,NaN,NaN,False,NaN,Compliant,Low outlier,NaN,NaN
freq,NaN,NaN,1460,987,3,4,3376,3376,NaN,8,...,NaN,NaN,NaN,NaN,3263,NaN,3211,23,NaN,NaN
mean,21208.991114,2016.0,NaN,NaN,NaN,NaN,NaN,NaN,98116.949107,NaN,...,1.086639e+06,3.707612e+06,1.368505e+04,1.368505e+06,NaN,NaN,NaN,NaN,119.723971,1.175916
std,12223.757015,0.0,NaN,NaN,NaN,NaN,NaN,NaN,18.615205,NaN,...,4.352478e+06,1.485066e+07,6.709781e+04,6.709781e+06,NaN,NaN,NaN,NaN,538.832227,1.821452
min,1.000000,2016.0,NaN,NaN,NaN,NaN,NaN,NaN,98006.000000,NaN,...,-3.382680e+04,-1.154170e+05,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,-0.800000,-0.020000
25%,19990.750000,2016.0,NaN,NaN,NaN,NaN,NaN,NaN,98105.000000,NaN,...,1.874229e+05,6.394870e+05,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,9.495000,0.210000
50%,23112.000000,2016.0,NaN,NaN,NaN,NaN,NaN,NaN,98115.000000,NaN,...,3.451299e+05,1.177583e+06,3.237538e+03,3.237540e+05,NaN,NaN,NaN,NaN,33.920000,0.610000
75%,25994.250000,2016.0,NaN,NaN,NaN,NaN,NaN,NaN,98122.000000,NaN,...,8.293178e+05,2.829632e+06,1.189033e+04,1.189034e+06,NaN,NaN,NaN,NaN,93.940000,1.370000
max,50226.000000,2016.0,NaN,NaN,NaN,NaN,NaN,NaN,98272.000000,NaN,...,1.925775e+08,6.570744e+08,2.979090e+06,2.979090e+08,NaN,NaN,NaN,NaN,16870.980000,34.090000

In [34]:
building_consumption['ListOfAllPropertyUseTypes'].value_counts()

ListOfAllPropertyUseTypes
Multifamily Housing                                                                       866
Multifamily Housing, Parking                                                              464
Office                                                                                    139
K-12 School                                                                               135
Office, Parking                                                                           120
                                                                                         ...
Other, Parking, Restaurant, Retail Store                                                    1
Non-Refrigerated Warehouse, Other, Parking, Retail Store                                    1
Data Center, Non-Refrigerated Warehouse, Office, Retail Store                               1
Data Center, Medical Office, Office, Parking, Restaurant                                    1
Fitness Center/Health Club/Gym, Office, Other - Recreation, Other - Technology/Science      1
Name: count, Length: 466, dtype: int64

#### TERMINER L'ANALYSE EXPLORATOIRE

A réaliser : 
- Une analyse descriptive des données, y compris une explication du sens des colonnes gardées, des arguments derrière la suppression de lignes ou de colonnes, des statistiques descriptives et des visualisations pertinentes.

Qelques pistes d'analyse :

* Identifier les colonnes avec une majorité de valeurs manquantes ou constantes en utilisant la méthode value_counts() de Pandas
* Mettre en evidence les différences entre les immeubles mono et multi-usages
* Utiliser des pairplots et des boxplots pour faire ressortir les outliers ou des batiments avec des valeurs peu cohérentes d'un point de vue métier

Pour vous inspirer, ou comprendre l'esprit recherché dans une analyse exploratoire, vous pouvez consulter ce notebook en ligne : https://www.kaggle.com/code/pmarcelino/comprehensive-data-exploration-with-python. Il ne s'agit pas d'un modèle à suivre à la lettre ni d'un template d'analyses attendues pour ce projet.

# Modélisation

### Import des modules

In [ ]:
#Selection
from sklearn.model_selection import (
    train_test_split,
    GridSearchCV, 
    cross_validate,
)
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error 
from sklearn.inspection import permutation_importance

#Preprocess
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler

#Modèles
from sklearn.dummy import DummyRegressor
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor

### Feature Engineering

A réaliser : Enrichir le jeu de données actuel avec de nouvelles features issues de celles existantes.

En règle générale : On utilise la méthode .apply() de Pandas pour créer une nouvelle colonne à partir d'une colonne existante. N'hésitez pas à regarder les exemples dans les chapitres de cours donnés en ressource

In [ ]:
# CODE FEATURE ENGINEERING

### Préparation des features pour la modélisation

A réaliser :
* Si ce n'est pas déjà fait, supprimer toutes les colonnes peu pertinentes pour la modélisation.
* Tracer la distribution de la cible pour vous familiariser avec l'ordre de grandeur. En cas d'outliers, mettez en place une démarche pour les supprimer.
* Débarrassez-vous des features redondantes en utilisant une matrice de corrélation de Pearson. Pour cela, utiisez la méthode corr() de Pandas, couplé d'un graphique Heatmap de la librairie Seaborn 
* Réalisez différents graphiques pour comprendre le lien entre vos features et la target (boxplots, scatterplots, pairplot si votre nombre de features numériques n'est pas très élevé).
*  Séparez votre jeu de données en un Pandas DataFrame X (ensemble de feautures) et Pandas Series y (votre target).
* Si vous avez des features catégorielles, il faut les encoder pour que votre modèle fonctionne. Les deux méthodes d'encodage à connaitre sont le OneHotEncoder et le LabelEncoder

In [ ]:
# CODE PREPARATION DES FEATURES

### Comparaison de différents modèles supervisés

A réaliser :
* Pour chaque algorithme que vous allez tester, vous devez :
    * Réaliser au préalable une séparation en jeu d'apprentissage et jeu de test via une validation croisée.
    * Si les features quantitatives que vous souhaitez utiliser ont des ordres de grandeur très différents les uns des autres, et que vous utilisez un algorithme de regression qui est sensible à cette différence, alors il faut réaliser un scaling (normalisation) de la donnée au préalable.
    * Entrainer le modèle sur le jeu de Train
    * Prédire la cible sur la donnée de test (nous appelons cette étape, l'inférence).
    * Calculer les métriques de performance R2, MAE et RMSE sur le jeu de train et de test.
    * Interpréter les résultats pour juger de la fiabilité de l'algorithme.
* Vous pouvez choisir par exemple de tester un modèle linéaire, un modèle à base d'arbres et un modèle de type SVM
* Déterminer le modèle le plus performant parmi ceux testés.

In [ ]:
# CODE COMPARAISON DES MODELES

### Optimisation et interprétation du modèle

A réaliser :
* Reprennez le meilleur algorithme que vous avez sécurisé via l'étape précédente, et réalisez une GridSearch de petite taille sur au moins 3 hyperparamètres.
* Si le meilleur modèle fait partie de la famille des modèles à arbres (RandomForest, GradientBoosting) alors utilisez la fonctionnalité feature importance pour identifier les features les plus impactantes sur la performance du modèle. Sinon, utilisez la méthode Permutation Importance de sklearn.

In [ ]:
# CODE OPTIMISATION ET INTERPRETATION DU MODELE