# Analyse Exploratoire

### Import des modules

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### Analyse Exploratoire

In [ ]:
building_consumption = pd.read_csv("data/raw/2016_Building_Energy_Benchmarking.csv")

In [ ]:
building_consumption

#### Audit du dataset

Vue d'ensemble

In [ ]:
# les dimensions (nb lignes , nb colonnes)
building_consumption.shape

In [ ]:
# Les informations générales sur le dataset , permet aussi de voir ou sont les valeurs nulles
# En comparant le nb de lignes et les non-null 
building_consumption.info()

In [ ]:
# Description détaillée de chaque colonne 
building_consumption.describe(include="all")

Qualité des données (nulls, doublons, valeurs aberrantes)

In [ ]:
# Details sur les nulls (colonne par colonne) 
df_nulls = building_consumption.isna().sum().reset_index()

# Renommage des colonnes pour une meilleure lisibilité + Affichage du dataframe
df_nulls.columns = ["variable", "nb_nulls"]
df_nulls

In [ ]:
# Nombre de lignes completes en doublon
building_consumption.duplicated().sum()

In [13]:
# building_consumption['BuildingType'].value_counts()
building_consumption['ComplianceStatus'].value_counts(dropna= False).reset_index()

               ComplianceStatus  count
0                     Compliant   3211
1  Error - Correct Default Data    113
2                 Non-Compliant     37
3                  Missing Data     15

#### Création du dataset allégé 
Les colonnes qui sont supprimées ont été au préalable analysées dans un document excel
<table>
  <thead>
    <tr>
      <th>À garder</th>
      <th>À supprimer</th>
      <th>Justification</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>YearBuilt</td>
      <td>OSEBuildingID</td>
      <td>L’identifiant unique n'est pas pertinent à garder car nous ne souhaitons pas identifier un batiment en particulier</td>
    </tr>
    <tr>
      <td>NumberofBuildings</td>
      <td>DataYear</td>
      <td>Pas utile<br>Toutes les lignes ont la même année : 2016<br><code>building_consumption['DataYear'].value_counts(dropna=False)</code></td>
    </tr>
    <tr>
      <td>NumberofFloors</td>
      <td>BuildingType</td>
      <td>Pas utile à garder pour l'analyse mais nécessaire pour filtrer les habitations pour ne pas les traiter</td>
    </tr>
    <tr>
      <td>PropertyGFATotal</td>
      <td>PrimaryPropertyType</td>
      <td>Pas nécessaire de les garder car la variable <code>ListOfAllPropertyUseTypes</code> le fait aussi et en mieux</td>
    </tr>
    <tr>
      <td>PropertyGFAParking</td>
      <td>PropertyName</td>
      <td>Pas nécessaire car pas besoin d'identifier un batiment en particulier</td>
    </tr>
    <tr>
      <td>PropertyGFABuilding(s)</td>
      <td>Address</td>
      <td>Pas besoin de cette information pour l'analyse</td>
    </tr>
    <tr>
      <td>ListOfAllPropertyUseTypes</td>
      <td>City</td>
      <td>Pas utile<br>Toutes les lignes ont la même année : Seattle<br><code>building_consumption['City'].value_counts(dropna=False)</code></td>
    </tr>
    <tr>
      <td>SiteEUI(kBtu/sf)</td>
      <td>State</td>
      <td>Pas utile<br>Toutes les lignes ont la même année : WA<br><code>building_consumption['City'].value_counts(dropna=False)</code></td>
    </tr>
    <tr>
      <td>SiteEnergyUse(kBtu)</td>
      <td>ZipCode</td>
      <td>Pas utile<br>Nous ne cherchons pas a savoir ou le batiment se situe (Seattle est suffisant)</td>
    </tr>
    <tr>
      <td>SteamUse(kBtu)</td>
      <td>TaxParcelIdentificationNumber</td>
      <td>Pas utile (tout comme l'identifiant unique)</td>
    </tr>
    <tr>
      <td>Electricity(kBtu)</td>
      <td>CouncilDistrictCode</td>
      <td>Pas utile<br>Nous ne cherchons pas a savoir ou le batiment se situe (Seattle est suffisant)</td>
    </tr>
    <tr>
      <td>NaturalGas(kBtu)</td>
      <td>Neighborhood</td>
      <td>Pas utile<br>Nous ne cherchons pas a savoir ou le batiment se situe (Seattle est suffisant)</td>
    </tr>
    <tr>
      <td>DefaultData</td>
      <td>Latitude</td>
      <td>Pas utile<br>Nous ne cherchons pas a savoir ou le batiment se situe (Seattle est suffisant)</td>
    </tr>
    <tr>
      <td>ComplianceStatus</td>
      <td>Longitude</td>
      <td>Pas utile<br>Nous ne cherchons pas a savoir ou le batiment se situe (Seattle est suffisant)</td>
    </tr>
    <tr>
      <td>Outlier</td>
      <td>LargestPropertyUseType</td>
      <td>Les surfaces de chaque type d'utilisation n'est pas nécessaire</td>
    </tr>
    <tr>
      <td>TotalGHGEmissions</td>
      <td>LargestPropertyUseTypeGFA</td>
      <td>Les surfaces de chaque type d'utilisation n'est pas nécessaire</td>
    </tr>
    <tr>
      <td></td>
      <td>SecondLargestPropertyUseType</td>
      <td>Les surfaces de chaque type d'utilisation n'est pas nécessaire</td>
    </tr>
    <tr>
      <td></td>
      <td>SecondLargestPropertyUseTypeGFA</td>
      <td>Les surfaces de chaque type d'utilisation n'est pas nécessaire</td>
    </tr>
    <tr>
      <td></td>
      <td>ThirdLargestPropertyUseType</td>
      <td>Les surfaces de chaque type d'utilisation n'est pas nécessaire</td>
    </tr>
    <tr>
      <td></td>
      <td>ThirdLargestPropertyUseTypeGFA</td>
      <td>Les surfaces de chaque type d'utilisation n'est pas nécessaire</td>
    </tr>
    <tr>
      <td></td>
      <td>YearsENERGYSTARCertified</td>
      <td>Pas utile[cite: 2]</td>
    </tr>
    <tr>
      <td></td>
      <td>ENERGYSTARScore</td>
      <td>Pas utile[cite: 2]</td>
    </tr>
    <tr>
      <td></td>
      <td>SiteEUIWN(kBtu/sf)</td>
      <td>Pas utile<br>La ligne SiteEUI(kBtu/sf) donne un résultat plus pertinent</td>
    </tr>
    <tr>
      <td></td>
      <td>SourceEUI(kBtu/sf)</td>
      <td>Pas utile , nous voulons savoir quelle energie consommée et non a la source</td>
    </tr>
    <tr>
      <td></td>
      <td>SourceEUIWN(kBtu/sf)</td>
      <td>Pas utile , nous voulons savoir quelle energie consommée et non a la source</td>
    </tr>
    <tr>
      <td></td>
      <td>SiteEnergyUseWN(kBtu)</td>
      <td>Pas utile , nous voulons savoir quelle energie consommée et non a la source</td>
    </tr>
    <tr>
      <td></td>
      <td>Electricity(kWh)</td>
      <td>Pas utile , la variable Electricity(kBtu) donne la meme information avec la bonne unité de mesure</td>
    </tr>
    <tr>
      <td></td>
      <td>NaturalGas(therms)</td>
      <td>Pas utile , la variable NaturalGas(kBtu) donne la meme information avec la bonne unité de mesure</td>
    </tr>
    <tr>
      <td></td>
      <td>Comments</td>
      <td>Pas utile car toutes vides<br><code>building_consumption['Comments'].value_counts(dropna=False)</code></td>
    </tr>
    <tr>
      <td></td>
      <td>GHGEmissionsIntensity</td>
      <td>Pas utile car nous mesurons le total et pas l'intensité des emission de gaz a effet de serre</td>
    </tr>
  </tbody>
</table>

In [9]:
#  Création d'un nouveau dataset 'copie' pour ne pas travailler sur l'original
building_consumption_light = building_consumption

#  Suppression des colonnes qui ne seront pas nécessaire a l'anayse exploratoire et au Machine Learning
building_consumption_light = building_consumption_light.drop([
                                                        'OSEBuildingID',
                                                        'DataYear',
                                                        'BuildingType',
                                                        'PrimaryPropertyType',
                                                        'PropertyName',
                                                        'Address',
                                                        'City',
                                                        'State',
                                                        'ZipCode',
                                                        'TaxParcelIdentificationNumber',
                                                        'CouncilDistrictCode',
                                                        'Neighborhood',
                                                        'Latitude',
                                                        'Longitude',
                                                        'LargestPropertyUseType',
                                                        'LargestPropertyUseTypeGFA',
                                                        'SecondLargestPropertyUseType',
                                                        'SecondLargestPropertyUseTypeGFA',
                                                        'ThirdLargestPropertyUseType',
                                                        'ThirdLargestPropertyUseTypeGFA',
                                                        'YearsENERGYSTARCertified',
                                                        'ENERGYSTARScore',
                                                        'SiteEUIWN(kBtu/sf)',
                                                        'SourceEUI(kBtu/sf)',
                                                        'SourceEUIWN(kBtu/sf)',
                                                        'SiteEnergyUseWN(kBtu)',
                                                        'Electricity(kWh)',
                                                        'NaturalGas(therms)',
                                                        'Comments',
                                                        'GHGEmissionsIntensity'], axis=1)

building_consumption_light

,YearBuilt,NumberofBuildings,NumberofFloors,PropertyGFATotal,PropertyGFAParking,PropertyGFABuilding(s),ListOfAllPropertyUseTypes,SiteEUI(kBtu/sf),SiteEnergyUse(kBtu),SteamUse(kBtu),Electricity(kBtu),NaturalGas(kBtu),DefaultData,ComplianceStatus,Outlier,TotalGHGEmissions
0,1927,1.0,12,88434,0,88434,Hotel,81.699997,7.226362e+06,2003882.00,3.946027e+06,1.276453e+06,False,Compliant,NaN,249.98
1,1996,1.0,11,103566,15064,88502,"Hotel, Parking, Restaurant",94.800003,8.387933e+06,0.00,3.242851e+06,5.145082e+06,False,Compliant,NaN,295.86
2,1969,1.0,41,956110,196718,759392,Hotel,96.000000,7.258702e+07,21566554.00,4.952666e+07,1.493800e+06,False,Compliant,NaN,2089.28
3,1926,1.0,10,61320,0,61320,Hotel,110.800003,6.794584e+06,2214446.25,2.768924e+06,1.811213e+06,False,Compliant,NaN,286.43
4,1980,1.0,18,175580,62000,113580,"Hotel, Parking, Swimming Pool",114.800003,1.417261e+07,0.00,5.368607e+06,8.803998e+06,False,Compliant,NaN,505.01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3371,1990,1.0,1,12294,0,12294,Office,69.099998,8.497457e+05,0.00,5.242709e+05,3.254750e+05,True,Error - Correct Default Data,NaN,20.94
3372,2004,1.0,1,16000,0,16000,Other - Recreation,59.400002,9.502762e+05,0.00,3.965461e+05,5.537300e+05,False,Compliant,NaN,32.17
3373,1974,1.0,1,13157,0,13157,"Fitness Center/Health Club/Gym, Other - Recrea...",438.200012,5.765898e+06,0.00,1.792159e+06,3.973739e+06,False,Compliant,NaN,223.54
3374,1989,1.0,1,14101,0,14101,"Fitness Center/Health Club/Gym, Food Service, ...",51.000000,7.194712e+05,0.00,3.488702e+05,3.706010e+05,False,Compliant,NaN,22.11
3375,1938,1.0,1,18258,0,18258,"Fitness Center/Health Club/Gym, Food Service, ...",63.099998,1.152896e+06,0.00,4.325542e+05,7.203420e+05,False,Compliant,NaN,41.27

In [12]:
# Création du CSV avec le dataset allégé
building_consumption_light.to_csv('data/Processed/building_consumption_light.csv')

#### Statistiques descriptives (sur le dataset 'allégé')

##### LES CORRELATIONS 
    SiteEnergyUse(kBtu)   =   SteamUse(kBtu) + Electricity(kBtu) + NaturalGas(kBtu)
    PropertyGFATotal   =   PropertyGFAParking + PropertyGFABuilding(s)

In [ ]:

# GRAPH sur le nb de buildings / annéesConstruction (paysage immobilier vieillisant ? ou non)
# GRAPH sur le le nb d'habitations VS nb d'autres types 
# GRAPH COMPARATIF : surface / consomation d'energie 
#                    surface / total emissions CO2

#### TERMINER L'ANALYSE EXPLORATOIRE

A réaliser : 
- Une analyse descriptive des données, y compris une explication du sens des colonnes gardées, des arguments derrière la suppression de lignes ou de colonnes, des statistiques descriptives et des visualisations pertinentes.

Qelques pistes d'analyse :

* Identifier les colonnes avec une majorité de valeurs manquantes ou constantes en utilisant la méthode value_counts() de Pandas
* Mettre en evidence les différences entre les immeubles mono et multi-usages
* Utiliser des pairplots et des boxplots pour faire ressortir les outliers ou des batiments avec des valeurs peu cohérentes d'un point de vue métier

Pour vous inspirer, ou comprendre l'esprit recherché dans une analyse exploratoire, vous pouvez consulter ce notebook en ligne : https://www.kaggle.com/code/pmarcelino/comprehensive-data-exploration-with-python. Il ne s'agit pas d'un modèle à suivre à la lettre ni d'un template d'analyses attendues pour ce projet.

# Modélisation

### Import des modules

In [ ]:
#Selection
from sklearn.model_selection import (
    train_test_split,
    GridSearchCV, 
    cross_validate,
)
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error 
from sklearn.inspection import permutation_importance

#Preprocess
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler

#Modèles
from sklearn.dummy import DummyRegressor
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor

### Feature Engineering

A réaliser : Enrichir le jeu de données actuel avec de nouvelles features issues de celles existantes.

En règle générale : On utilise la méthode .apply() de Pandas pour créer une nouvelle colonne à partir d'une colonne existante. N'hésitez pas à regarder les exemples dans les chapitres de cours donnés en ressource

In [ ]:
# CODE FEATURE ENGINEERING

### Préparation des features pour la modélisation

A réaliser :
* Si ce n'est pas déjà fait, supprimer toutes les colonnes peu pertinentes pour la modélisation.
* Tracer la distribution de la cible pour vous familiariser avec l'ordre de grandeur. En cas d'outliers, mettez en place une démarche pour les supprimer.
* Débarrassez-vous des features redondantes en utilisant une matrice de corrélation de Pearson. Pour cela, utiisez la méthode corr() de Pandas, couplé d'un graphique Heatmap de la librairie Seaborn 
* Réalisez différents graphiques pour comprendre le lien entre vos features et la target (boxplots, scatterplots, pairplot si votre nombre de features numériques n'est pas très élevé).
*  Séparez votre jeu de données en un Pandas DataFrame X (ensemble de feautures) et Pandas Series y (votre target).
* Si vous avez des features catégorielles, il faut les encoder pour que votre modèle fonctionne. Les deux méthodes d'encodage à connaitre sont le OneHotEncoder et le LabelEncoder

In [ ]:
# CODE PREPARATION DES FEATURES

### Comparaison de différents modèles supervisés

A réaliser :
* Pour chaque algorithme que vous allez tester, vous devez :
    * Réaliser au préalable une séparation en jeu d'apprentissage et jeu de test via une validation croisée.
    * Si les features quantitatives que vous souhaitez utiliser ont des ordres de grandeur très différents les uns des autres, et que vous utilisez un algorithme de regression qui est sensible à cette différence, alors il faut réaliser un scaling (normalisation) de la donnée au préalable.
    * Entrainer le modèle sur le jeu de Train
    * Prédire la cible sur la donnée de test (nous appelons cette étape, l'inférence).
    * Calculer les métriques de performance R2, MAE et RMSE sur le jeu de train et de test.
    * Interpréter les résultats pour juger de la fiabilité de l'algorithme.
* Vous pouvez choisir par exemple de tester un modèle linéaire, un modèle à base d'arbres et un modèle de type SVM
* Déterminer le modèle le plus performant parmi ceux testés.

In [ ]:
# CODE COMPARAISON DES MODELES

### Optimisation et interprétation du modèle

A réaliser :
* Reprennez le meilleur algorithme que vous avez sécurisé via l'étape précédente, et réalisez une GridSearch de petite taille sur au moins 3 hyperparamètres.
* Si le meilleur modèle fait partie de la famille des modèles à arbres (RandomForest, GradientBoosting) alors utilisez la fonctionnalité feature importance pour identifier les features les plus impactantes sur la performance du modèle. Sinon, utilisez la méthode Permutation Importance de sklearn.

In [ ]:
# CODE OPTIMISATION ET INTERPRETATION DU MODELE